# Assignment-3 — UCS420 "Cognitive Computing"
## Pandas

## Q.1 Create a dataset as shown in the table

In [1]:
import pandas as pd
import numpy as np

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                        "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                        "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df.set_index("Tid", inplace=True)
df

    Refund Marital Status Taxable Income Cheat
Tid
1      Yes         Single           125K    No
2       No        Married           100K    No
3       No         Single            70K    No
4      Yes        Married           120K    No
5       No       Divorced            95K   Yes
6       No        Married            60K    No
7      Yes       Divorced           220K    No
8       No         Single            85K   Yes
9       No        Married            75K    No
10      No         Single            90K   Yes

## Q.2 Locate row 0, 4, 7 and 8 using DataFrame
Using `.iloc[]` since these are positional (0-indexed) row locations.

In [2]:
df.iloc[[0, 4, 7, 8]]

    Refund Marital Status Taxable Income Cheat
Tid
1      Yes         Single           125K    No
5       No       Divorced            95K   Yes
8       No         Single            85K   Yes
9       No        Married            75K    No

## Q.3 Navigate the DataFrame

### 3.1 Select rows from index 3 to 7

In [3]:
df.iloc[3:8]

    Refund Marital Status Taxable Income Cheat
Tid
4      Yes        Married           120K    No
5       No       Divorced            95K   Yes
6       No        Married            60K    No
7      Yes       Divorced           220K    No
8       No         Single            85K   Yes

### 3.2 Select rows from index 4 to 8, and columns 2 to 4

In [4]:
df.iloc[4:9, 2:5]

    Taxable Income Cheat
Tid
5              95K   Yes
6              60K    No
7             220K    No
8              85K   Yes
9              75K    No

### 3.3 Select all rows with column index 1 to 3 (include index 3 during selection)

In [5]:
df.iloc[:, 1:4]

    Marital Status Taxable Income Cheat
Tid
1           Single           125K    No
2          Married           100K    No
3           Single            70K    No
4          Married           120K    No
5         Divorced            95K   Yes
6          Married            60K    No
7         Divorced           220K    No
8           Single            85K   Yes
9          Married            75K    No
10          Single            90K   Yes

## Q.4 Read a CSV file and display its first five rows
Dataset: [Iris dataset](https://www.kaggle.com/datasets/uciml/iris) (`Iris.csv`, uploaded in the same folder as this notebook).

In [6]:
iris_df = pd.read_csv("Iris.csv")
iris_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Q.5 Delete row 4 and delete column 3 from the CSV, then display the result

In [7]:
iris_modified = iris_df.drop(index=4)          # delete row with index 4
iris_modified = iris_modified.drop(columns=iris_modified.columns[3])  # delete column at position 3
iris_modified.head(10)

    Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0    1            5.1           3.5           0.2  Iris-setosa
1    2            4.9           3.0           0.2  Iris-setosa
2    3            4.7           3.2           0.2  Iris-setosa
3    4            4.6           3.1           0.2  Iris-setosa
5    6            5.4           3.9           0.4  Iris-setosa
6    7            4.6           3.4           0.3  Iris-setosa
7    8            5.0           3.4           0.2  Iris-setosa
8    9            4.4           2.9           0.2  Iris-setosa
9   10            4.9           3.1           0.1  Iris-setosa
10  11            5.4           3.7           0.2  Iris-setosa

## Q.6 Create a sample dataset (`employees.csv`)

In [8]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

emp_df = pd.DataFrame(employee_data)
emp_df.to_csv("employees.csv", index=False)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### a) Shape (number of rows and columns) of the DataFrame

In [9]:
emp_df.shape

(5, 10)

### b) Summary of the DataFrame — data types and non-null counts

In [10]:
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

### c) Generate descriptive statistics

In [11]:
emp_df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

### d) Display the first 5 rows and last 3 rows of the dataset

In [12]:
print("First 5 rows:")
display(emp_df.head())

print("\nLast 3 rows:")
display(emp_df.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### e) Calculate statistics from the dataset

In [13]:
avg_salary = emp_df["Salary"].mean()
total_bonus = emp_df["Bonus"].sum()
youngest_age = emp_df["Age"].min()
highest_rating = emp_df["Rating"].max()

print(f"i.   Average salary of employees: {avg_salary}")
print(f"ii.  Total bonus paid to all employees: {total_bonus}")
print(f"iii. Youngest employee's age: {youngest_age}")
print(f"iv.  Highest performance rating: {highest_rating}")

i.   Average salary of employees: 60000.0
ii.  Total bonus paid to all employees: 27500
iii. Youngest employee's age: 28
iv.  Highest performance rating: 4.7

### f) Sort the DataFrame by the Salary column in descending order

In [14]:
emp_df_sorted = emp_df.sort_values(by="Salary", ascending=False)
emp_df_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### g) Add a new column that categorizes employees by performance rating

In [15]:
def categorize_rating(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

emp_df["Performance_Category"] = emp_df["Rating"].apply(categorize_rating)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### h) Identify missing values in the DataFrame

In [16]:
emp_df.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### i) Rename the Employee_ID column to ID

In [17]:
emp_df.rename(columns={"Employee_ID": "ID"}, inplace=True)
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### j) Find all employees who:

**i. Have more than 5 years of experience**

In [18]:
emp_df[emp_df["Years_of_Experience"] > 5]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

**ii. Belong to the IT department**

In [19]:
emp_df[emp_df["Department"] == "IT"]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

### k) Add a new column, Tax, which deducts 10% of the Salary

In [20]:
emp_df["Tax"] = emp_df["Salary"] * 0.10
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

### l) Save the modified DataFrame (with added columns) to a new CSV file

In [21]:
emp_df.to_csv("employees_modified.csv", index=False)
print("Saved to employees_modified.csv")

# Verify by reading it back
pd.read_csv("employees_modified.csv")

Saved to employees_modified.csv

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0